###
GET http://localhost:8000/api


###
GET http://localhost:8000/api/timeout



//fetch all users
###
GET  http://localhost:8000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5NSwidXNlcm5hbWUiOiJBbW9vIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjA3ODk4NjksImV4cCI6MTcyMDc5MzQ2OX0.uaVzTPeUyMeQc5bXUAmWNL4n6trWD78rR0hU_52Jz5c


//fetching one user
###
GET  http://localhost:8000/api/users/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5NSwidXNlcm5hbWUiOiJBbW9vIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjA3ODk4NjksImV4cCI6MTcyMDc5MzQ2OX0.uaVzTPeUyMeQc5bXUAmWNL4n6trWD78rR0hU_52Jz5c



//updaing a user
###
PUT   http://localhost:8000/api/users/3
Content-Type: application/json

{
    "fullName": "Joel Dae"
}



###
POST http://localhost:8000/api/users
Content-Type: application/json

{   
    
"full_name": "Lyn Dave",
  "email": "Lyne@example.com",
  "contact_phone": "(157) 459-7890",
  "address": "100 Main Street, Nax, CA 12945",
  "role": "user",
  "password": "admin34884",
    "created_at": "2024-07-04 ",
    "updated_at": "2024-07-04"
}

//Deleting a user
###
DELETE http://localhost:5000/api/users/5




### Bookings
//fetch all bookings
GET http://localhost:8000/api/bookings



//fetching one booking
###
GET  http://localhost:8000/api/bookings/9


###
POST http://localhost:8000/api/bookings/9
Content-Type: application/json

{
  
  "booking_id": 9,
  "user_id": 1,
  "vehicle_id": 1,
  "location_id": 1,
  "booking_date": "2024-07-15",
  "return_date": "2024-07-20",
  "total_amount": "200.00",
  "booking_status": "Pending",
  "created_at": "2024-07-04 12:36:13.384034",
  "updated_at": "2024-07-04 12:36:13.384034"
  
}


###
PUT http://localhost:8000/api/bookings/9
Content-Type: application/json

{
   
    "bookingStatus": "Pending"
    
}


###
DELETE http://localhost:5000/api/bookings/9



### Customer Support Tickets
GET http://localhost:8000/api/customer-support-tickets




###
POST http://localhost:8000/api/customer-support-tickets



###
PUT http://localhost:8000/api/customer-support-tickets/1



###
DELETE http://localhost:8000/api/customer-support-tickets/2




### Fleet Management
GET http://localhost:8000/api/fleet-management



###
POST http://localhost:8000/api/fleet-management
Content-Type: application/application/json

{
    "vehicle_id": 1,
    "acquisition_date": "2022-01-01",
    "depreciation_rate": "0.10",
    "current_value": "18000.00",
    "maintenance_cost": "1500.00",
    "status": "Active",
     "created_at": "2024-07-04 12:40:01.461811",
    "updated_at": "2024-07-04 12:40:01.461811"
}



###
DELETE http://localhost:8000/api/fleet-management/1




### Locations
GET http://localhost:8000/api/locations





### Locations
GET http://localhost:8000/api/locations/1




###
POST http://localhost:8000/api/locations
Content-Type: application/json
{
     "locationId": 10,
    "name": "Sub Branch",
    "address": "1123 main Street, Anytawn, CA 223345",
    "contactPhone": "(125) 555-1221",
    "createdAt": "2023-07-04 09:53:01.534061",
    "updatedAt": "2023-07-04 09:53:01.534061"
}



###
PUT http://localhost:8000/api/locations/1




###
DELETE http://localhost:8000/api/locations/2


### Payments
GET http://localhost:8000/api/payments

###
GET http://localhost:8000/api/payments/1


###
POST http://localhost:5000/api/payments
Content-Type: application/json

{
    "booking_id": 10,
    "booking_id": 4,
    "amount": "220.00",
    "payment_status": "Pending",
    "payment_date": 2024-07-04,
    "payment_method": "Credit Card",
    "transaction_id": 10

}

###
DELETE http://localhost:8000/api/payments/2




# Vehicles
### 
GET http://localhost:8000/api/vehicles


###
POST http://localhost:8000/api/vehicles/3


###
PUT http://localhost:8000/api/vehicles/1
Connection: 



###
DELETE http://localhost:8000/api/vehicles/2


### Vehicle Specifications
GET  http://localhost:8000/api/vehicle-specifications


GET http://localhost:8000/api/vehicle-specifications
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5NSwidXNlcm5hbWUiOiJBbW9vIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MjA3OTA3NTcsImV4cCI6MTcyMDc5NDM1N30.92Ft44wTKki5zEEKZvhVJL_JmdINRUbvyu-B7whl-38

###
POST http://localhost:8000/api/vehicle-specifications






### Admin Registration

POST http://localhost:8000/api/signup
Content-Type: application/json

{
    "user_id": 5,
    "full_name": "amos amoo",
    "email": "amoo@gmail.com",  
    "contact_phone": "(123) 451-7090",
    "address": "123 Main Street, Anytoa, CA 12345",
     "username": "Amoo",
    "password": "Amoo1234",
    "role": "admin"
}

### Admin Login

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "username": "Amoo",
    "password": "Amoo1234"
}